spring:
  # app 이름
  application:
    name: demo
  
  # 메시지 국제화 설정
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: true
    default-locale: ko
    
  # HTTP 인코딩 설정
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  # 오라클 연동
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: c##spring
    password: spring1234
  # SQL 스크립트 자동 실행 설정
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql

  # Elasticsearch 설정 (테스트용)
  elasticsearch:
    uris: localhost:9200
    username: elastic
    password: admin1234
    # Elasticsearch 연결 실패 시에도 애플리케이션 시작 허용
    connection-timeout: 5000
    socket-timeout: 10000

  # 파일 업로드 설정
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true
      file-size-threshold: 2KB
      location: ${java.io.tmpdir}
  #ai
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      
  # 이메일 설정 (Gmail SMTP 예시)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# 웹서버 포트
server:
  port: 9082
  # HTTP 인코딩 설정
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#서버 세션 타임아웃 설정
#기본은 1800(30분), 최소값 60(1분)
    session:
      timeout: 60
#클라이언트의 세션아이디를 서버가 받는 방식
#1. 클라이언트의 쿠키정보를 읽어 요청할때마다 요청메세지 헤더에 세션아이디를 취득
#2. 클라이언트의 쿼리스트링을 읽어 세션아이디를 취득
      tracking-mode: cookie

# 파일 업로드 설정
file:
  upload:
    path: ${user.dir}/uploads
    allowed-image-types: jpg,jpeg,png,gif,webp
    allowed-document-types: pdf,doc,docx,txt
    max-image-size: 10MB
    max-document-size: 10MB

# 로그레벨
# trace > debug > info > warn > error > fatal
logging:
  level:
    # 제거할 설정 (JPA/Hibernate 관련)
    org.hibernate.SQL: DEBUG    # ❌ 불필요
    org.hibernate.type: TRACE   # ❌ 불필요
    
    # 유지할 설정
    org.springframework.jdbc: WARN     # NamedParameterJdbcTemplate 로그
    org.elasticsearch.client.RestClient: DEBUG    # Elasticsearch 로그
    org.apache.http.wire: DEBUG                  # HTTP 요청/응답 로그
    com.kh.demo: DEBUG                           # 애플리케이션 로그

