DROP USER c##spring CASCADE;
CREATE USER c##spring IDENTIFIED BY spring1234 DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp PROFILE DEFAULT;
GRANT CONNECT, RESOURCE TO c##spring;
GRANT CREATE VIEW, CREATE SYNONYM TO c##spring;
GRANT UNLIMITED TABLESPACE TO c##spring;
ALTER USER c##spring ACCOUNT UNLOCK;